Hide ToC contents when hidden
JuliaPluto/PlutoUI.jl pull request #209
Opened 2022-05-05 11:34 UTC by disberd

This very small change simply reduce the ToC height to only show the closed book icon when the ToC is hidden. 
This is done to minimize the vertical clutter of the ToC (now that the ToC does not remove its aside status automatically anymore) when the main text is very close to the edge of the browser.
See https://github.com/fonsp/Pluto.jl/issues/1770 for example.
 
New behavior example:
![89547624-f1ae-476c-91ba-297ce8e19e96](https://user-images.githubusercontent.com/12846528/166915143-ad952102-6a8f-420c-a4a5-24b35be6dbed.gif)

2022-05-05 12:41 UTC, pankgeorg requested changes

2022-05-05 12:41 UTC, pankgeorg commented on src/TableOfContents.jl
> +	height: 57px;
Love this! Instead of hide, do we have some HTML structure we can `display:none` on?

2022-05-05 12:42 UTC, pankgeorg commented on src/TableOfContents.jl
> +	height: 57px;
You can keep the height too (and maybe add animation! (css transform)), on top of the `display:none`

2022-05-05 13:06 UTC, disberd commented on src/TableOfContents.jl
> +    	margin-bottom: 0em;
This would actually need to be `-0.1em` to be simmetric with the top margin, but I found out that it looks more simmetric like this on my laptopt

2022-05-09 10:26 UTC, pankgeorg approved these changes

2022-05-19 10:22 UTC, merged